export const details = {
    cuisine: [
        "American",
        "Chinese",
        "French",
        "Greek",
        "Japanese",
        "Korean",
        "Italian",
        "Mexican",
        "Thai",
        "Pizza",
        "Other",
    ],
    location: [
        "New York",
        "Brooklyn",
        "Queens",
        "Bronx",
        "Manhattan",
        "Staten Island",
        "Long Island",
        "Boston",
        "D.C.",
    ],
};
